# Generated by Django 3.2.23 on 2024-02-14 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0049_alter_touristiccontentcategory_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touristiceventorganizer',
            name='label',
            field=models.CharField(max_length=256, unique=True, verbose_name='Label'),
        ),
    ]
